#custom aliases by Maarten
alias x='chmod +x'
alias ealias='vim -p ~/.bash_aliases'
alias apt='sudo apt-get install'
alias upgrade='sudo apt-get upgrade'
alias remove='sudo apt-get purge'
alias update='sudo apt-get update'
alias search='apt-cache search'
alias autoremove='sudo apt-get autoremove'
alias repo='sudo add-apt-repository'
alias down='cd /home/maarten/Downloads'
alias up='cd ..'
alias ds='dropbox start'
alias vimrc='vim ~/.vimrc'
alias cl='clear'
alias exp='nautilus . &'
alias rc='vim ~/.bashrc'
alias ssh='ssh -t -X -C'
alias ipy='ipython -i'
alias py='python'
alias ma='mathematica'
alias ls='ls --color'
alias l='ls -CF --color'
alias ltr='ls -ltr --color'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias awmrc='vim ~/essentials/.config/awesome/rc.lua'
alias zz='sudo pm-suspend'
alias reboot='sudo reboot'
alias halt='sudo poweroff'
alias tree='tree -D'
