#custom aliases by Maarten
alias up='cd ..'
alias x='chmod +x'
alias htmltidy='tidy -wim'
alias run='R CMD BATCH'
alias aliases='vim -p ~/.bash_aliases'
alias apt='sudo apt-get install'
alias upgrade='sudo apt-get upgrade'
alias remove='sudo apt-get purge'
alias update='sudo apt-get update'
alias search='apt-cache search'
alias autoremove='sudo apt-get autoremove'
alias repo='sudo add-apt-repository'
alias down='cd /home/maarten/Downloads'
alias up='cd ..'
alias ds='dropbox start'
alias ptidy='perl $HOME/CustomScripts/tidyreplace.pl'
alias downloads='cd /home/maarten/Downloads'
alias vimrc='vim ~/.vimrc'
alias cl='clear'
alias exp='nautilus . &'
alias rc='vim ~/.bashrc'
alias ssh='ssh -t -C'
alias matlab='matlab -nosplash -nodesktop'
alias ipy='ipython qtconsole ipy &'
alias py='python'
alias gvim='gvim -font "Monospace 9"'
alias ma='mathematica'
alias ls='ls --color'
alias ll='ls -alF --color'
alias la='ls -A --color'
alias l='ls -CF --color'
alias lf='ls -ltr | grep -ve "~$"'
alias ltr='ls -ltr --color'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
